name: Integration Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/oplyx-tech-server -f ./server/Dockerfile ./server

      - name: Push Docker Image
        run: docker push ${{secrets.DOCKER_USERNAME}}/oplyx-tech-server:latest
